import localFont from "next/font/local";
import "./globals.css";
import Sidebar1 from './Components/Sidebar/Sidebar1'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ `antialiased`}
      >
     <div className="fel">
        <div>
            <Sidebar1/>
        </div>
        <div>
            {children}
        </div>
    </div>
      </body>
    </html>
  );
}
